# Generated by Django 4.1.5 on 2023-01-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_alter_answer_question_alter_question_quiz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quizzes",
            name="category",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quizzes",
        ),
    ]
