# Generated by Django 4.1.5 on 2023-01-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
